name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is master
  workflow_dispatch: # Allows you to trigger the build manually

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Crucial Step: This uploads only your 'docs' folder, preserving all 3+ levels of nesting
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './knowledge_base' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
